services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 2 -b 0.0.0.0:8000 wsgi:app
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/microloans
      PORT: "8000"
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    networks:
      - loans_net


  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: microloans
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d microloans"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - loans_net

  nginx:
    image: nginx:latest
    depends_on:
      api:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    networks:
      - loans_net


networks:
  loans_net:
    driver: bridge

volumes:
  db_data:
