services:
  api:
    build: .
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      FLASK_ENV: ${FLASK_ENV}
      LOG_LEVEL: ${API_LOG_LEVEL}
      DATABASE_URL: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      PORT: ${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        alembic upgrade head &&
        gunicorn -w 2 -b 0.0.0.0:${API_PORT} wsgi:app
      "
    networks:
      - loans_net

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_INIT_DB_NAME}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
      - db_data_staging:/var/lib/postgresql/data
      - db_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${POSTGRES_INIT_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - loans_net

  nginx:
    profiles: ["staging", "production"]
    image: nginx:latest
    depends_on:
      api:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/certs:ro
    networks:
      - loans_net

networks:
  loans_net:
    driver: bridge

volumes:
  db_data_dev:
  db_data_staging:
  db_data_prod:

